rr_lib/wake_up/__init__.py
S_BAD = "BAD"
S_OK = "OK"

STEP_TIME = 60 * 10
WAIT_TO_RAISE = 60

cfg_group = "wake_up"

rr_lib/wake_up/views.py
import logging
import socket

from flask import request, Blueprint, render_template
from flask.json import jsonify
from wake_up import STEP_TIME

from wake_up.engine import WakeUp
from rr_lib.states.process_director import ProcessDirector

wake_up_app = Blueprint('wake_up_api', __name__, template_folder="templates")

log = logging
wu = WakeUp()
pd = ProcessDirector('wake_up')

aspect = "wake_up_%s" % socket.gethostbyname(socket.gethostname())
if not pd.is_aspect_work(aspect, timing_check=False):
    wu.start()
    pd.start_aspect(aspect, tick_time=STEP_TIME / 2, with_tracking=False)


@wake_up_app.route("/<salt>", methods=["POST"])
def wake_up(salt):
    return jsonify(**{"result": salt})


@wake_up_app.route("/check")
def wake_up_check():
    wu.check()
    urls = map(lambda x: {"url": x.get("url", ), "state": x.get("state", )}, wu.store.get_urls_info())
    return jsonify({"ok": True, "urls": urls})


@wake_up_app.route("/", methods=["GET", "POST"])
def wake_up_manage():
    if request.method == "POST":
        urls = request.form.get("urls", )
        urls = filter(lambda x: x, map(lambda x: x.strip(), urls.split("\n")))

        stored_urls = wu.store.get_urls()
        to_delete = set(stored_urls).difference(urls)
        deleted_count = wu.store.delete_urls(to_delete)
        log.info("Delete %s urls" % deleted_count)
        for url in urls:
            wu.store.add_url(url)

    urls = wu.store.get_urls()

    return render_template("wake_up_.html", **{"urls": urls})

rr_lib/wake_up/wake_up/__init__.py
S_BAD = "BAD"
S_OK = "OK"

STEP_TIME = 60*10
WAIT_TO_RAISE = 60

cfg_group = "wake_up"

rr_lib/wake_up/wake_up/views.py
import logging
import socket

from flask import request, Blueprint, render_template
from flask.json import jsonify
from wake_up import STEP_TIME

from wake_up.engine import WakeUp
from rr_lib.states.process_director import ProcessDirector

wake_up_app = Blueprint('wake_up_api', __name__, template_folder="templates")

log = logging
wu = WakeUp()
pd = ProcessDirector('wake_up')

aspect = "wake_up_%s" % socket.gethostbyname(socket.gethostname())
if not pd.is_aspect_work(aspect, timing_check=False):
    wu.start()
    pd.start_aspect(aspect, tick_time=STEP_TIME / 2, with_tracking=False)


@wake_up_app.route("/<salt>", methods=["POST"])
def wake_up(salt):
    return jsonify(**{"result": salt})


@wake_up_app.route("/check")
def wake_up_check():
    wu.check()
    urls = map(lambda x: {"url": x.get("url"), "state": x.get("state")}, wu.store.get_urls_info())
    return jsonify({"ok": True, "urls": urls})


@wake_up_app.route("/", methods=["GET", "POST"])
def wake_up_manage():
    if request.method == "POST":
        urls = request.form.get("urls")
        urls = filter(lambda x: x, map(lambda x: x.strip(), urls.split("\n")))

        stored_urls = wu.store.get_urls()
        to_delete = set(stored_urls).difference(urls)
        deleted_count = wu.store.delete_urls(to_delete)
        log.info("Delete %s urls" % deleted_count)
        for url in urls:
            wu.store.add_url(url)

    urls = wu.store.get_urls()

    return render_template("wake_up.html", **{"urls": urls})

rr_lib/wake_up/templates/wake_up.html
{% extends "layout.html" %}
{% block body %}

{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-8 col-md-offset-2" id="content">
            <h2>Поднималка-с</h2>
            <hr>
            <button class="btn btn-lg btn-info" id="wake-up-check" onclick="wu_check();">
                Восподнять-c
            </button>
            <hr>
            <form class="form-horizontal" id="urls-form" action="{{url_for('wake_up_api.wake_up_manage')}}" method="post">
                <div class="form-group">
                    <div class="col-md-12">
                        <textarea name="urls" rows="6" class="textarea">
                            {%for url in urls%}
                            {{url}}
                            {%endfor%}
                        </textarea>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-12">
                        <button class="submit btn btn-info btn-lg" type="submit">Постановить</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6 col-md-offset-2">
            <img id='loader-gif' src="{{url_for('static', filename='img/giphy.gif')}}">
        </div>
    </div>
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <table class="table table-stripped sortable">
                <thead><tr><td>Url</td><td>State</td></tr> </thead>
                <tbody id="urls-states">

                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}
<script>
    function wu_check(){
       $("#loader-gif").show();
       $.ajax({
        url:"/wake_up/check",
        success:function(data){
           if (data.ok){
            $('#urls-states').empty();
            data.urls.forEach(function(url){
                $('#urls-states').append("<tr><td>"+url.url+"</td><td>"+url.state+"</td></tr>");
            });
             $("#loader-gif").hide();
           }
        }
       });
  }


</script>

{%endblock%}